trigger:
  - master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "vs2017-win2016"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - bash: yarn install --frozen-lockfile
    displayName: Install
  - bash: yarn test
    displayName: Run Tests
  - bash: yarn run test-client-integration
    displayName: Integration Tests
    env:
      DISPLAY: ":99.0"
# cspell:ignore macos xvfb
